### ISSUE TITLE
Explain where to place the code, or at least comment file at the top.

### ISSUE THREAD

**Issue by JonHill24** [shawntabrizi/substrate-collectables-workshop#104]
I believe it would be really beneficial if you comment where each block of code should be placed. I have found many instances in chapter 1 where a block of code is shown, but where it belongs in the code base is not specified.

**Comment by shawntabrizi** [comment]
@JonHill24 Can you give a specific example?

**Comment by JonHill24** [comment]
@shawntabrizi I was viewing the code under "Declaring a Storage Value" & didn't realize it wasn't meant to be implemented and was just an example. Will look to provide more relevant issues, my apologies.

**Comment by shawntabrizi** [comment]
Yeah, in general, my tutorials are more in favor of teaching you some concept in general, and then having you apply it yourself.

If we provide the correct copy paste code, I am afraid people will not actually use their brains and write things out themself.
