### ISSUE TITLE
[Suggestion] Use `squash and merge` for PR to get clearer commit records

### ISSUE THREAD

**Issue by koushiro** [shawntabrizi/substrate-collectables-workshop#105]

**Comment by shawntabrizi** [comment]
Is this something we can do retroactively?

**Comment by koushiro** [comment]
Yes, just merge the trivial commits in the PR into a commit, you can choose to keep the appropriate commit messages.

**Comment by shawntabrizi** [comment]
I have disabled merge commits so all merges should be squashed from this point forward

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1860335/58705971-03571700-83b1-11e9-99a3-7b3410501299.png">

**Comment by koushiro** [comment]
Sorry, maybe I didn't express it clearly. I mean that every PR  should correspond to every commit of the master branch.
