### ISSUE TITLE
Should breeding a kitty use checked_add for incremented gen value?

### ISSUE THREAD

**Issue by todofixthis** [shawntabrizi/substrate-collectables-workshop#122]
In https://substrate.dev/substrate-collectables-workshop/#/3/breeding-a-kitty the solution uses the following code to set the new kitty's `gen` value:

```rust
            let new_kitty = Kitty {
                ...
                gen: cmp::max(kitty_1.gen, kitty_2.gen) + 1,
            };
```

Should this logic be using `checked_add()` instead (concept introduced in [chapter 2](https://substrate.dev/substrate-collectables-workshop/#/2/tracking-all-kitties?id=checking-for-overflowunderflow))?  E.g.:

```rust
            let kitty_1 = Self::kitty(kitty_id_1);
            let kitty_2 = Self::kitty(kitty_id_2);

            let new_gen = cmp::max(kitty_1.gen, kitty_2.gen).checked_add(1)
                .ok_or("Overflow when incrementing offspring kitty's generation number.")?;

            ...

            let new_kitty = Kitty {
                ...
                gen: new_gen,
            };
```

I'm new to Rust and Substrate, so I don't know if this is a special case where `checked_add()` is not necessary — then this would be an opportunity to reinforce the principle (or explain the special case).

**Comment by shawntabrizi** [comment]
It should be used here too for safety. However, in this case `gen` can never be greater than the number of kitties in the system. And both `gen` and `total_kitties_count` use the same `u64` to store the value.

If we introduced kitty deletion, then we may have a problem... either way, doing `saturated_add` is probably what we want here. Basically it will get to a max value, and not increase anymore.
