### ISSUE TITLE
problem for app.jsx

### ISSUE THREAD

**Issue by ecslew** [shawntabrizi/substrate-collectables-workshop#136]
Hello,

After running the app.jsx in your workshop, it did not work with the following problems:
![Screenshot from 2019-09-21 18-59-23](https://user-images.githubusercontent.com/19843228/65381238-fa60bd00-dca1-11e9-9fa7-9d2976bdb884.png)

Would you like to help me to fix it out?

Best regards,

Edward

**Comment by shawntabrizi** [comment]
Do you have a storage item called "AllKittiesArray" in your runtime module?

**Comment by ecslew** [comment]
Yes. I do

**Comment by shawntabrizi** [comment]
I don't think I can assist you without you providing reproducible steps.

You should look to debug your runtime apis using the console.
