### ISSUE TITLE
A 'TypeError’ occurs when use Substrate UI

### ISSUE THREAD

**Issue by Eanam** [shawntabrizi/substrate-collectables-workshop#146]
When I learn the lesson about how to develop  cryptokitties ,there is a problem I dont know why,
here is the problem: 
 when I use the Substarte UI ,and  I came to #Web-UI -> Creating Kitties ，the problem occurred when I input the command ''post({
    sender: '5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ',
    call: calls.substratekitties.createKitty()
}).tie(console.log)"   ,it return "Uncaught (in promise) TypeError: Cannot read property 'constructor' of null";

and here is a simple stack :
codec.js:662 Uncaught (in promise) TypeError: Cannot read property 'constructor' of null
    at encode (codec.js:662)
    at eval (codec.js:474)
    at Array.map (<anonymous>)
    at encode (codec.js:474)
    at encode (codec.js:510)
    at eval (transact.js:44)
    at new Promise (<anonymous>)
    at composeTransaction (transact.js:17)
    at eval (transact.js:113)
    at TransformBond.eval (transformBond.js:111)

**Comment by mitsu1124** [comment]
Hi, actually I have the same problem as above.

Pleasure if someone could help us out.

![image](https://user-images.githubusercontent.com/45583595/70277624-16322480-17f6-11ea-92ee-a7748e8bdb49.png)

**Comment by Eanam** [comment]
> Hi, actually I have the same problem as above.
> Relating to it or not, CreateKitty button is disabled.
> 
> Pleasure if someone could help us out.
> 
> ![image](https://user-images.githubusercontent.com/45583595/70277624-16322480-17f6-11ea-92ee-a7748e8bdb49.png)

Hi , actually I alreay fixed the problem .
It is not caused by the code , It is caused by the operations that has not been written in the substratekitties course.
below is waht you need to do before you do all the operations in the Gav's Substrate UI 
**add the seed And Name** 
_add the accout exists since initial development_
for example :Alice's seed is //Alice , AliceStash's seed is //Alice//stash
![image](https://user-images.githubusercontent.com/39086937/70294288-f3b40180-181d-11ea-9071-33edaffc20ab.png)
_add the accout which is created by yourself_
![image](https://user-images.githubusercontent.com/39086937/70296091-4bee0200-1824-11ea-8c97-41af3d35d9b8.png)

**Comment by mitsu1124** [comment]
Hi @Eanam ,
glad for your support. It seems it worked for me. Very very appreciated.

![image](https://user-images.githubusercontent.com/45583595/70329992-f7787000-187f-11ea-8484-4ad80ad8795a.png)
