### ISSUE TITLE
init.sh uses wasm-gc which is no longer supported by the original author

### ISSUE THREAD

**Issue by Mikerah** [shawntabrizi/substrate-collectables-workshop#160]
I have been having trouble following the tutorial as is due to the fact that `init.sh` doesn't complete on my machine. Upon further research, it looks like this `init.sh` scripts makes use of [wasm-gc](https://github.com/alexcrichton/wasm-gc) which according to the original repo is deprecated as Rust and other wasm libraries already support its functionality. 

Even though this tutorial covers an outdated version of substrate, I think it's really good and provides a more complex and realistic example of how to build a substrate chain, instead of the very simple PoE example on the substrate hub website. As such, I think it would be nice to still have certain components up to date with the newest version of substrate, especially as the API is solidifying, somewhat.

**Comment by shawntabrizi** [comment]
When 2.0 stable is released, I will then look to update the tutorial. Until then, unfortunately it will stay outdated, but still has plenty to teach.

In terms of the `init.sh` script, what is the specific error you are getting?

**Comment by Mikerah** [comment]
Thank you very much. I will gladly wait for the update!

Here's part of the log output from running `init.sh`:
```
error: could not rename component file from '/home/mikerah/.rustup/tmp/ojo7vaaipjya0p4__dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share'
error: could not rename component file from '/home/mikerah/.rustup/tmp/159yt51d93ad7gn9_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc'
error: could not rename component file from '/home/mikerah/.rustup/tmp/ip454r7m1ovkm0vs_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/man'
error: could not rename component file from '/home/mikerah/.rustup/tmp/xkohtuo_qmme7sgm_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu'
error: could not rename component file from '/home/mikerah/.rustup/tmp/0qhdy76lhrclcdhx_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/zsh'
error: could not rename component file from '/home/mikerah/.rustup/tmp/ywaebrv4f51t6t5u_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/etc'
error: could not rename component file from '/home/mikerah/.rustup/tmp/q2zklst30p_o3j9a_dir/bk' to '/home/mikerah/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown'
error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
Sometimes not all components are available in any given nightly.
```

**Comment by Mikerah** [comment]
I was able to get over the issue I was having. I'm currently in the midst of porting this tutorial to Substrate v2.0. Closing.
