### ISSUE TITLE
Various errors while trying to port this workshop to Substrate 2.x

### ISSUE THREAD

**Issue by Mikerah** [shawntabrizi/substrate-collectables-workshop#161]
Since this workshop was written for the previous large release of Substrate (Substrate 1.0), I have been attempting to port it over to Substrate 2.0 while learning both Substrate and Rust. I have encountered the following errors while trying to do this:

1. ```associated type `Balance` not found```
I get this error when my lib.rs file looks like:
```
#![cfg_attr(not(feature = "std"), no_std)]

/// A FRAME pallet template with necessary imports

/// Feel free to remove or edit this file as needed.
/// If you change the name of this file, make sure to update its references in runtime/src/lib.rs
/// If you remove this file, you can remove those references

/// For more guidance on Substrate FRAME, see the example pallet
/// https://github.com/paritytech/substrate/blob/master/frame/example/src/lib.rs

use frame_support::{
	decl_module, decl_storage, decl_event, dispatch,
};
use frame_system::{self as system, ensure_signed};
use codec::{Encode, Decode};
use sp_runtime::traits::Hash;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[derive(Encode, Decode, Default, Clone, PartialEq)]
#[cfg_attr(feature = "std", derive(Debug))]
pub struct Kitty<Hash, Balance> {
	id: Hash,
	dna: Hash,
	price: Balance,
	gen: u64,
}

/// The pallet's configuration trait.
pub trait Trait: system::Trait{
	/// The overarching event type.
	type Event: From<Event<Self>> + Into<<Self as system::Trait>::Event>;
}

decl_event! {
    pub enum Event<T> where AccountId = <T as system::Trait>::AccountId {
		SomethingStored(u32, AccountId),
    }
}

// This pallet's storage items.
decl_storage! {
	// It is important to update your storage name so that your pallet's
	// storage items are isolated from other pallets.
	// ---------------------------------
	trait Store for Module<T: Trait> as KittyStorage {
		OwnedKitty get(fn get_kitter_owner): map hasher(blake2_128_concat) T::AccountId => Kitty<T::Balance, T::Hash>;
	}
}


// The pallet's dispatchable functions.
decl_module! {
	/// The module declaration.
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {

		#[weight = 10_000]
		fn create_kitty(origin) -> dispatch::DispatchResult {
			let _sender = ensure_signed(origin);
			let new_kitty = Kitty {
				id: <T as system::Trait>::Hashing::hash_of(&0),
				dna: <T as system::Trait>::Hashing::hash_of(&0),
				price: (0 as u64).into(),
				gen: 0,
			};

			OwnedKitty::<T>::insert(&_sender, new_kitty);

			Ok(())
		}
	
	}
	
}
```
2. When changing ``` T::Balance``` to ```<T as balances::Trait>::Balance```, I get the following four errors
```error: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `panic_impl`.```
```error: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `oom`.```
```error[E0277]: the trait bound `T: pallet_balances::Trait` is not satisfied```
3. When changing ```pub trait Trait: system::Trait``` to ```pub trait Trait: system::Trait + balances::Trait``` or ```pub trait Trait: balances::Trait + system::Trait```, I get the following errors:
```error: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `panic_impl`.```
```error: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `oom`.```
```error[E0221]: ambiguous associated type `Hash` in bounds of `T````
```error[E0221]: ambiguous associated type `AccountId` in bounds of `T````
```error[E0221]: ambiguous associated type `BlockNumber` in bounds of `T````
```error[E0221]: ambiguous associated type `BlockNumber` in bounds of `T````
```error[E0221]: ambiguous associated type `BlockNumber` in bounds of `T````
```error[E0221]: ambiguous associated type `Origin` in bounds of `T````

I should also note that I'm using the [substrate node template](https://github.com/substrate-developer-hub/substrate-node-template) and all of this is in the `pallet` directory as opposed to the `runtime` directory as originally done in Substrate 1.0. 

Also, here's my `Cargo.tml` file:
```
[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-rc3'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc3'
version = '2.0.0-rc3'

[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template'
edition = '2018'
homepage = 'https://substrate.io'
license = 'Unlicense'
name = 'pallet-template'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '2.0.0-rc3'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'balances/std',
    'sp-runtime/std',
]
```

**Comment by JoshOrndorff** [comment]
Your last two errors `duplicate lang item` mean that you have either brought `std` into your runtime, or used two different versions of substrate somewhere. These errors should be solved first and may solve your other errors as well.

Start by ensuring that every Substrate dependency in any of your `Cargo.toml` files uses the same version. Then ensure that every dependency in your runtime is brought in with `default-features = false` and that the dependency is added to the `std` feature.

Also FYI, some others have also started updating this code https://github.com/SubstrateCourse/substrate-kitties

**Comment by Mikerah** [comment]
Resolved most of these errors. Onto other ones...
