### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by J-Cook-jr** [shawntabrizi/substrate-collectables-workshop#163]
<img width="1280" alt="Screen Shot 2021-02-25 at 12 06 25 PM" src="https://user-images.githubusercontent.com/62865359/109189343-ea37f180-7761-11eb-849c-78518ec9b48e.png">

I'm currently following the crypto collectables tutorial: https://www.shawntabrizi.com/substrate-collectables-workshop/#/0/running-a-custom-node
I'm getting the error above after entering this command :
./scripts/build.sh

Can you help me out? Thanks!

**Comment by lsaul** [comment]
Encountered the same issue. I found this thread, via the error, but haven't had luck switching the rust version. 

https://github.com/substrate-developer-hub/substrate-node-template/issues/90

Maybe someone who knows Rust better can help. I'll update if I figure it out.

**Comment by amitdua048** [comment]
![image](https://user-images.githubusercontent.com/43226599/115116884-a15e2580-9fb9-11eb-9383-c167d5819ab1.png)


Encountered the same issue in MacOS M1

**Comment by amitdua048** [comment]
![image](https://user-images.githubusercontent.com/43226599/115128126-36344380-9ff9-11eb-90a4-6e3d3b0acca5.png)




![image](https://user-images.githubusercontent.com/43226599/115128191-9d51f800-9ff9-11eb-931f-d21e7c2533f6.png)



Encountered similar error while running on WSL ubuntu 20.04 even after following the solutions suggested at substrate-developer-hub/substrate-node-template#90

**Comment by amitdua048** [comment]
![image](https://user-images.githubusercontent.com/43226599/116024134-2eb11200-a66b-11eb-831a-76ec60ef23ea.png)

![image](https://user-images.githubusercontent.com/43226599/116024252-6ddf6300-a66b-11eb-99cd-76b90d4419f9.png)

Encountered the same error in stand alone Ubuntu 20.04 while executing the ./scripts/build.sh in running-a-custom-node

**Comment by AgainstLightning** [comment]
I too am running into this, hoping for some direction! 🤞 

- Windows 10 WSL2
- Ubuntu 20.04.2 LTS
- rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by arturgontijo** [comment]
I think I fixed this, by freezing rustc versions, at:
https://github.com/shawntabrizi/substrate-package/pull/45
