### ISSUE TITLE
Substrate v3.0 Code

### ISSUE THREAD

**Issue by ddimaria** [shawntabrizi/substrate-collectables-workshop#164]
I went through the tutorial up to the end of [#3](https://www.shawntabrizi.com/substrate-collectables-workshop/#/3/playing-our-game) and rewrote it in Substrate v3.0.  I posted the code here: https://github.com/ddimaria/substrate-collectables-workshop-template

If I have time, I'll add in Tests and Extras.   I'll also attempt to update this repo to use the latest version, time permitting.

**Comment by shawntabrizi** [comment]
@ddimaria thanks for doing this.

One catch is that unfortunately the runtime patterns in the tutorial are not quite what we would want to teach to new developers.

The real solution is to rewrite everything from scratch and even redesign the pallet to be more storage efficient...

but if you do complete this work, i think it would be worth to merge given how much people ask for it.

**Comment by rlaferla** [comment]
This tutorial absolutely needs to be updated to explain the latest version of Substrate.

e.g.  https://www.shawntabrizi.com/substrate-collectables-workshop/#/1/creating-a-storage-value is using FRAME v1.
