### ISSUE TITLE
Links for switching sections doesn't take you to the top of the page

### ISSUE THREAD

**Issue by HCastano** [shawntabrizi/substrate-collectables-workshop#17]
When clicking the "Next"/"Previous" buttons throughout the tutorial I expect to land on the top of the next/previous page. Right now I land somewhere in the middle.

**Comment by shawntabrizi** [comment]
fixed with https://github.com/shawntabrizi/substrate-collectables-workshop/commit/4a8fd3180679629d7c603f0d1c60e6bd3a3db50b

Using: https://docsify.js.org/#/configuration?id=auto2top
