### ISSUE TITLE
Hyperlinks, grammatical corrections and missing solution files

### ISSUE THREAD

**Issue by mittal-parth** [shawntabrizi/substrate-collectables-workshop#171]
### Grammar

- [x] When _a_ callable function ....
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/8/README.md?plain=1#L5

- [x] Can be reworded - These use cases make sense because all the logic in our pallet typically touches only one key at a time on average.
https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/17/README.md?plain=1#L65

- [x] Now that we have _the_ tools .... , `MaxEndodedLen`
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/25/README.md?plain=1#L79

### Hyperlinks

- [x] Links should be hyperlinks otherwise they appear as plain text.
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/11/README.md?plain=1#L7-L9

- [x] https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/15/README.md?plain=1#L9-L11

- [x] https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/13/README.md?plain=1#L85-L87

- [x] https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/13/README.md?plain=1#L114-L116

- [x] https://github.com/shawntabrizi/substrate-collectables-workshop/blob/f22cee7db250a5ecc0e1f00372962e050ab0f529/steps/31/README.md?plain=1#L37

### Docs Hyperlinks

- [x] Might as well hyperlink the docs for uniformity/completeness. `StorageMap`
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/17/README.md?plain=1#L9

- [x] `get(key)` https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/18/README.md?plain=1#L13-L15

- [x] `pallet_balances`: https://github.com/shawntabrizi/substrate-collectables-workshop/blob/f22cee7db250a5ecc0e1f00372962e050ab0f529/steps/38/README.md?plain=1#L13

### Misc 
- [x] Can be left for the reader to add instead of just asking to learn as the 'You Turn' sections talks about adding one.
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/17/src/lib.rs#L24-L26

- [x] Again, can be left to the reader to implement with a solution diff provided.
  https://github.com/shawntabrizi/substrate-collectables-workshop/blob/f22cee7db250a5ecc0e1f00372962e050ab0f529/steps/38/src/lib.rs#L23-L24

- [x] Same as above (not just that line, but all the diff on that page). Has a changes.diff file instead of the usual template.diff and solution.diff
  https://www.shawntabrizi.com/substrate-collectables-workshop/26/index.html

  https://github.com/shawntabrizi/substrate-collectables-workshop/blob/f22cee7db250a5ecc0e1f00372962e050ab0f529/steps/39/src/lib.rs#L28

- [x] This should either be marked as a TODO or something is missing? 
 https://github.com/shawntabrizi/substrate-collectables-workshop/blob/4851c309fee758eea7796a94e52897d6a96107be/steps/7/README.md?plain=1#L29

- [x] The declaration of the `encoded_payload` is somewhat inconsistent. Should ideally be kept as:

  `let encoded_payload: Vec<u8> = unique_payload.encode();`, everywhere.

  https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/28/src/impls.rs#L16

  https://github.com/shawntabrizi/substrate-collectables-workshop/blob/ea7ccc33d384c52c6b7dc958827567321f97dca6/steps/39/src/impls.rs#L17

- [x] Maybe add some message at the end of the tutorial? Optional but I think its nice to have :)

I can help with these with a PR.

**Comment by shawntabrizi** [comment]
@mittal-parth this is exactly the kind of stuff i am looking for.

thank you!

>  This should either be marked as a TODO or something is missing?

Yes mark as `TODO: `

PR is welcome

**Comment by shawntabrizi** [comment]
>  Can be left for the reader to add instead of just asking to learn as the 'You Turn' sections talks about adding one.

Yeah, in this case, I can make it a `template -> solution` step instead of just an "action".

**Comment by shawntabrizi** [comment]
>  Maybe add some message at the end of the tutorial? Optional but I think its nice to have :)

Yes, I will add a `Next Steps` as a final section of the tutorial.

**Comment by shawntabrizi** [comment]
I fixed all issues except grammar and docs hyperlinks.

I will let you make PRs for that if you like.

**Comment by mittal-parth** [comment]
> I fixed all issues except grammar and docs hyperlinks.
> 
> I will let you make PRs for that if you like.

Sure, I'll make a PR in about an hour

**Comment by mittal-parth** [comment]
@shawntabrizi made a PR via #172
