### ISSUE TITLE
Limit the "section" to be one para sellers

### ISSUE THREAD

**Issue by iammasterbrucewayne** [shawntabrizi/substrate-collectables-workshop#173]
**Problem:** The dotcodeschool interface treats gitorial "sections" as milestone markers and doesn't expect them to have the meaty content that should be included in the tutorial steps itself.

**Proposed Solution:** Limiting the "section" to only have one short and sweet paragraph description would fix this without requiring a complete redesign of the interface.

**Screenshots:**
Short description:
<img width="400" alt="Screenshot 2024-08-06 at 12 31 03 PM" src="https://github.com/user-attachments/assets/0b66635b-5ce8-43c1-b70b-74c5cac1e6ac">

The "Next Steps" section was considered "empty" by the interface and content for "Introduction" was skipped:
<img width="400" alt="Screenshot 2024-08-06 at 12 34 38 PM" src="https://github.com/user-attachments/assets/b8e57fbe-a22e-4a15-94c0-f041a37a9788">

<img width="341" alt="Screenshot 2024-08-06 at 12 34 52 PM" src="https://github.com/user-attachments/assets/eba449c3-9e26-4df9-8669-2cf17cc97eda">

**Comment by shawntabrizi** [comment]
i updated the main 4 sections, but not next steps.

I don't think it makes sense to have a sub task for next steps, so something like this perhaps you should handle on your side, or just ignore the page.
