### ISSUE TITLE
Is this tut made specific for "Dot Code School"? if so, should we reference that? thx for the love man.

### ISSUE THREAD

**Issue by zzz6519003** [shawntabrizi/substrate-collectables-workshop#181]

**Comment by shawntabrizi** [comment]
Dot Code School was made to host this kind of tutorial with a slightly better UI.

This tutorial lives independent of dot code school, and can be adopted to any other platforms.

There are people who have repurposed this tutorial for other projects too.

**Comment by zzz6519003** [comment]
this can be made like a protocol lol

**Comment by shawntabrizi** [comment]
@zzz6519003 it is already: https://github.com/gitorial-sdk

if you would want to contribute, there is a lot to be done.

**Comment by zzz6519003** [comment]
what a wild idea!
