### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by hippiestank** [shawntabrizi/substrate-collectables-workshop#189]
[Step 31 - src/impls.rs](https://github.com/shawntabrizi/substrate-collectables-workshop/blob/master/steps/31/src/impls.rs): Line 3 -> primitives misspelled

[Step 40 - src/impls.rs](https://github.com/shawntabrizi/substrate-collectables-workshop/blob/master/steps/40/src/impls.rs): Line 47 -> extra space

**Comment by shawntabrizi** [comment]
tyvm fixed here: https://github.com/shawntabrizi/substrate-collectables-workshop/commit/c8c2e0f98b53f5bec4cb001f9c5cf1ec990bbd8b
