### ISSUE TITLE
Distinction between Merkle Tree vs Merkle Trie?

### ISSUE THREAD

**Issue by Madalosso** [shawntabrizi/substrate-collectables-workshop#192]
[Chapter 10, Storage, Markle Trie](https://github.com/shawntabrizi/substrate-collectables-workshop/blob/mdbook/src/10/source/README.md#merkle-trie) section refers to "Merkle Trie" to describe what I believe is commonly referred as as Merkle Tree.

Using "Merkle Trie" might create confusion due to the "trie" term being commonly associated with prefix trees, which matches a Merkle Patricia Trie for storage. 

I take it that the objective of this section is to focus on the Merkle Tree root hash calculation and how it can be used to validate the database's state between nodes, so I suggest adopting the "Merkle Tree" name.

It might be worth adding a new section to distinguish these two and how they are used.

**Comment by Madalosso** [comment]
Also, I'm not sure of the accuracy of the last line:
> It is called a merkle "trie" because the trie data structure is used to reduce the amount of redundant data stored in the tree.

**Comment by shawntabrizi** [comment]
Substrate uses this trie library:

https://github.com/paritytech/trie

Which is indeed a trie, not a tree.

If I understand your comments, it might be that I over generalize the usage of tries in blockchains, but certainly every optimized Blockchain should use a trie over a tree because it literally saves space.

**Comment by Madalosso** [comment]
Interesting. Thanks for the clarification. I'll go through the library and try to resolve my confusion. 
Feel free to close this ticket, or we can keep it open until I understand it better and propose a segment to address the possible overgeneralization.

**Comment by shawntabrizi** [comment]
If you have a suggestion, feel free to re-open :)
