### ISSUE TITLE
Math check on Storage Hash Fingerprint section

### ISSUE THREAD

**Issue by Madalosso** [shawntabrizi/substrate-collectables-workshop#193]
https://github.com/shawntabrizi/substrate-collectables-workshop/tree/master/steps/11#hash-fingerprint

> For context, a 32-byte hash has 2^32 different possible outputs. This is nearly as many atoms as there are in the whole universe!

Shouldn't this be 2^256 instead?

**Comment by shawntabrizi** [comment]
@Madalosso haha yes :)

Do you want to submit a PR? or I can do it :)

**Comment by Madalosso** [comment]
I had this one opened for a few days https://github.com/shawntabrizi/substrate-collectables-workshop/pull/191
But today I realized that I was probably doing the change targeting the wrong branch (mdbook).
I can create a new one soon with the fix :)

**Comment by Madalosso** [comment]
@shawntabrizi, there it is.
Thanks for the workshop, It was very useful to learn with a hands-on approach

**Comment by shawntabrizi** [comment]
thanks for your feedback and contribution!
