### ISSUE TITLE
Missing info about fees to store values in runtime storage (1.5)

### ISSUE THREAD

**Issue by Stefie** [shawntabrizi/substrate-collectables-workshop#33]
Add info at the end of chapter 1.5, that you need to transfer a minimum balance of 1000 from Alice to the other accounts to be able to store values in runtime storage

https://shawntabrizi.github.io/substrate-collectables-workshop/#/1/1.5-viewing-a-storage-mapping

**Comment by shawntabrizi** [comment]
Stale.
