### ISSUE TITLE
Expand description of `Result`

### ISSUE THREAD

**Issue by shawntabrizi** [shawntabrizi/substrate-collectables-workshop#34]
Many people got the import wrong dispatch::Result.
We should communicate this more clearly. Not sure how actually.
Also people had questions about Rust's ? operator and the oddly looking Ok(()) at the end.

**Comment by akhanaton** [comment]
Getting error below when following your instructions:

error[E0308]: mismatched types                                                                         
  --> /mnt/d/ubuntu projects/substratekitties/runtime/src/substratekitties.rs:15:45                    
   |                                                                                                   
15 |         fn set_value(origin, value: u64) -> Result {                                              
   |            ---------                        ^^^^^^ expected enum `core::result::Result`, found () 
   |            |                                                                                      
   |            this function's body doesn't return                                                    
...                                                                                                    
20 |             Ok(());                                                                               
   |                   - help: consider removing this semicolon                                        
   |                                                                                                   
   = note: expected type `core::result::Result<(), &'static str>`                                      
              found type `()`    


Looks like its trying to use the wrong type?

**Comment by shawntabrizi** [comment]
@akhanaton In Rust, you omit the semi-colon when you want to return a value from a function. In this case, module functions should return `Ok(())` when they complete successfully, so you should not have a semi-colon at the end.

Take a read here: https://doc.rust-lang.org/book/ch03-03-how-functions-work.html#function-bodies-contain-statements-and-expressions

```
Note the x + 1 line without a semicolon at the end, which is unlike most of the lines you’ve seen so far. Expressions do not include ending semicolons. If you add a semicolon to the end of an expression, you turn it into a statement, which will then not return a value. Keep this in mind as you explore function return values and expressions next.
```

**Comment by akhanaton** [comment]
@shawntabrizi  Thanks, that solved it.

**Comment by shawntabrizi** [comment]
This has been addressed in tiny.cc/substrate-getting-started

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1860335/56538552-a96a6280-6563-11e9-9cd6-db06d6c17420.png">
