### ISSUE TITLE
Explain what the macros do

### ISSUE THREAD

**Issue by jaybutera** [shawntabrizi/substrate-collectables-workshop#40]
After reading through the tutorial I understand how to build the functions and storage for a module with the ```decl_storage!``` and ```decl_module!``` macros, but I don't understand what is actually being built by the macros. It would be great to have a section that explains some of the inner workings.

For the storage macro, what are the "for" and "as" words expressing?
```trait Store for Module<T: Trait> as KittyStorage {```

What is the structure of a Module and Storage? We really only see a glimpse of their existence in the ```construct_runtime!``` macro with ```Substratekitties: substratekitties::{Module, Call, Storage}```

Similarly for ```decl_module!```, what is ```enum Call```?
```pub struct Module<T: Trait> for enum Call where origin: T::Origin {```

**Comment by shawntabrizi** [comment]
@jaybutera more in progress

https://substrate.readme.io/docs/construct_runtime

**Comment by shawntabrizi** [comment]
@jaybutera `decl_module` here:
https://substrate.readme.io/v1.0.0/docs/decl_module
