### ISSUE TITLE
Explain <T as system::Trait>...

### ISSUE THREAD

**Issue by shawntabrizi** [shawntabrizi/substrate-collectables-workshop#42]
https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name

**Comment by yjkimjunior** [comment]
Hey @shawntabrizi I'd like to tackle this in the context the last couple of points of this blog series thingamajiggy - https://medium.com/@yjkim_44736/dumb-rust-questions-of-a-js-developer-building-substrate-runtimes-substrate-kitties-workshop-7ef72621059a

Currently re-reading the rust book - will follow up with a draft here.

**Comment by shawntabrizi** [comment]
@yjkimjunior sounds awesome :)

Note that this would probably be "extra" learning material, so feel free to go a little deep and out of context of the substrate kitties module. It will live likely somewhere at the end of one of the sections
