### ISSUE TITLE
Integrate Rust Playground

### ISSUE THREAD

**Issue by shawntabrizi** [shawntabrizi/substrate-collectables-workshop#44]

**Comment by gnunicorn** [comment]
Something like the [`run` button in the rust cookbooks](https://rust-lang-nursery.github.io/rust-cookbook/algorithms/randomness.html#generate-random-numbers) would be awesome.

**Comment by ltfschoen** [comment]
Other references with similar functionality:
* app-js package of Polkadot-JS Apps https://polkadot.js.org/apps/#/js
* https://github.com/parity-js/dapp-console
