### ISSUE TITLE
A Chinese translation of the tutorial

### ISSUE THREAD

**Issue by koushiro** [shawntabrizi/substrate-collectables-workshop#52]
I am translating this tutorial into Chinese version because of my interest.
Now I have completed README and Section 0 in [branch/zh-cn-dev](https://github.com/koushiro/substrate-collectables-workshop/tree/zh-cn-dev) of my fork.
Hope it could help some Chinese developer who are interested in the `Substrate`.

**Comment by koushiro** [comment]
The Chinese translation of the tutorial has been finished on the [branch zh-cn](https://github.com/koushiro/substrate-collectables-workshop/tree/zh-cn).

**Comment by shawntabrizi** [comment]
@koushiro Do you want to make a pull request? :)

Do you have a friend or community member you know who can peer review your stuff?

uhhh, and THANKS by the way :) 💯 ❤️

**Comment by jiangfuyao** [comment]
@shawntabrizi I would love to do.

**Comment by jiangfuyao** [comment]
<https://github.com/koushiro/substrate-collectables-workshop/pull/2>

**Comment by jiangfuyao** [comment]
This is a very careful translation, Looks good. :+1:

**Comment by koushiro** [comment]
@shawntabrizi I will make a PR after my work is reviewed by my friends and community members :)

**Comment by shawntabrizi** [comment]
@koushiro I am going to update the tutorial for Substrate 1.0, at which point is should remain pretty stable for the foreseeable future. Would you be interested in making some final changes and opening a pull request to the main repo?

**Comment by koushiro** [comment]
@shawntabrizi I'd be glad to do this.

**Comment by shawntabrizi** [comment]
Want to start with a PR? No reason not to try and get things merged

**Comment by koushiro** [comment]
> Want to start with a PR? No reason not to try and get things merged

Yes, but I need to update some changes firstly.

**Comment by shawntabrizi** [comment]
I made some fixes to get everything working:
https://github.com/shawntabrizi/substrate-collectables-workshop/commit/4a8fd3180679629d7c603f0d1c60e6bd3a3db50b

But looks like now we have a fully translated tutorial!

<3 @koushiro
