### ISSUE TITLE
Explanation on creating custom event trait

### ISSUE THREAD

**Issue by hskang9** [shawntabrizi/substrate-collectables-workshop#59]
I think it would be better to have more explanation to build custom type event on [creating an event](https://shawntabrizi.github.io/substrate-collectables-workshop/#/2/creating-an-event)

For example, if I want to make a Transfer event `Transfer(AccountId, Price, data)`:

Specify what name will be used in the event,
in cryptokitties.rs,
```rust
decl_event!(
    pub enum Event<T>
    where
        <T as system::Trait>::AccountId,
    {
       Transfer(AccountId, u128, String)
    }
);
```

**Comment by shawntabrizi** [comment]
@hskang9 I guess I am a little confused exactly what you mean here. Is your goal to create an event which contains a custom defined type?

Or are you trying to figure out how exactly you can modify the `Event` type for some other purpose? If so, what is that purpose?

What is `Trial`?

**Comment by hskang9** [comment]
1. My bad for confusion. I was figuring out how to modify event, because I wanted to put more information in the events than given types(e.g. Balance, AccountId). After watching the [event](https://github.com/paritytech/substrate/blob/63388a466a7d9069a83e47e37e8aa173e37736ed/srml/support/src/event.rs) code, I found out that it does not require modifying`Event` type, but I wonder if there is given types for basic types such as string, byte array, etc. 
2. Trial was the variable to figure out.

**Comment by shawntabrizi** [comment]
@hskang9 Do you think you could make a quick/rough draft of what kind of content you think should be included?

I am still a little disconnected from exactly what you are looking for. Would it be sufficient to show the example in your comment somewhere in the docs showing that it works?

```
decl_event!(
    pub enum Event<T>
    where
        <T as system::Trait>::AccountId,
    {
       Transfer(AccountId, u128, String)
    }
);
```

**Comment by hskang9** [comment]
I was thinking it would be better if the developer can create their own event for breeding a kitty without using only designated type from built-in traits(e.g. Hash, Balance). There can also be `String` output for event to describe the kitty, or `u64` for notifying the kitty's generation, which is important for the kitty's valuation. Otherwise, the client will have to throttle to look up the kitty's information after it is created while the runtime can just tell the client after the process.

I have tested creating rust built-in type events on  substrate [here](https://github.com/decentral-inc/nyc-blockchain-workshop/blob/master/Topic2/03_wasm_in_substrate/substrate-tutorial/runtime/src/tutorial.rs), and I would like to know if there is a way to declare a custom event trait just as other given trait does.

For the draft on the content to be included, instead of `Created(AccountId, Hash)` event, I will try to submit PR with the instruction on how to add your own rust built-in type or named event trait so that the event can express more information on the substrate.
