### ISSUE TITLE
Add production link to repo description

### ISSUE THREAD

**Issue by ltfschoen** [shawntabrizi/substrate-collectables-workshop#6]
Edit the description of the repo https://github.com/shawntabrizi/substrate-collectables-workshop so instead of just saying "A guided tutorial for building a collectable token chain on Parity Substrate", it says that but also provides a link to a live version of it i.e.  "A guided tutorial for building a collectable token chain on Parity Substrate https://shawntabrizi.github.io/substrate-collectables-workshop/"

**Comment by shawntabrizi** [comment]
Updated the "website" link for the repo
