### ISSUE TITLE
Minor UX improvements for the layout

### ISSUE THREAD

**Issue by kirushik** [shawntabrizi/substrate-collectables-workshop#61]
1. Make sure "Next" button is always available, so users won't have to look in the sidebar on the left to continue reading at the end of each chapter.
2. When clicking "Next" button or navigating to the next chapter, the content area scroll should reset, so I don't end peeking the end of the next subchapter after scrolling down the previous one. (Bonus points for actually _remembering_ the scroll position of the last/each content page, so after accidental click on Next I won't reset my progress in the subchapter).

**Comment by shawntabrizi** [comment]
#2 was fixed with https://github.com/shawntabrizi/substrate-collectables-workshop/commit/4a8fd3180679629d7c603f0d1c60e6bd3a3db50b

Using: https://docsify.js.org/#/configuration?id=auto2top

**Comment by shawntabrizi** [comment]
#1 has an open issue on the plugin here:
https://github.com/imyelo/docsify-pagination/issues/12

**Comment by shawntabrizi** [comment]
1. has been solved with this!
https://github.com/imyelo/docsify-pagination/pull/14
