### ISSUE TITLE
Unused method:make_transfer is used in Kitty Tutorial

### ISSUE THREAD

**Issue by ookimaki** [shawntabrizi/substrate-collectables-workshop#75]
Hi I'm following substrate kitty tutorial. 

In below tutorial, make_transfer method is used to transfer coin when buying kitty.
https://shawntabrizi.github.io/substrate-collectables-workshop/#/3/buying-a-kitty
<balances::Module<T>>::make_transfer(&from, &to, value)?;

However when I use make_transfer, I face following error.
`
error[E0599]: no function or associated item named make_transfer found for type srml_balances::Module<T> in the current scope
  --> /usr/src/app/ohinerichain/runtime/src/template.rs:72:36
   |
72 |             <balances::Module<T>>::make_transfer(origin, &owner, price)?;
   |                                    ^^^^^^^^^^^^^ function or associated item not found in srml_balances::Module<T>
`

I found out make_transfer method is no longer available after this commit.
https://github.com/paritytech/substrate/commit/cc8f93c029698cf0d91ee6a10a65b3990fa38734

Can you please suggest how we can do this kind of simple transfer instead of make_transfer and fix tutorial?

**Comment by ookimaki** [comment]
Oh, excuse me, this issue seems already asked in substrate technical Riot chat room.

I fixed this issue by adding 'traits::{Currency}' in 'use support::...' and change '<balances::Module>::make_transfer(&from, &to, value)?;' to '<balances::Module<T> as Currency<_>>::transfer(&sender, &owner, kitty.price)?;' and now it is compiled!

And also it is mentioned that this tutorial will be updated later, so this issue is self-closed.

**Comment by shawntabrizi** [comment]
Fixed with https://github.com/shawntabrizi/substrate-collectables-workshop/commit/fe749249e6410154e02f7a76472bda898f56a84b
