### ISSUE TITLE
Japanese translation of the tutorial

### ISSUE THREAD

**Issue by tokyoweb3** [shawntabrizi/substrate-collectables-workshop#77]
I am translating this tutorial into Japanese so that more developers in Japan find it less daunting and join substrate/polkadot community.
I've already created the repo [branch/ja-JP](https://github.com/MasakiMinamide/substrate-collectables-workshop/tree/ja-JP), and am expecting one~two weeks are needed for completion of translation.
If anyone interested in peer review, please leave a comment on this issue.

**Comment by shawntabrizi** [comment]
This is awesome. Please reach out to me for any assistance I can provide!
