### ISSUE TITLE
Two oddities for declaring a struct?

### ISSUE THREAD

**Issue by JoshOrndorff** [shawntabrizi/substrate-collectables-workshop#91]
https://github.com/shawntabrizi/substrate-collectables-workshop/blob/master/1/storing-a-structure.md#defining-a-custom-struct mentions "two oddities". I can't figure out how to link to a specific line in an `md` file, so let this screenshot suffice.

![image](https://user-images.githubusercontent.com/2915325/57089554-f89f5880-6d04-11e9-80d4-6f994fe14372.png)

Are the two oddities
1. Encode
2. Decode

Or was it supposed to be
1. Encode and Decode
2. `#[cfg_attr(feature = "std", derive(Debug))]`

**Comment by shawntabrizi** [comment]
The two oddities i believe are meant to be the `Using Generics` and `Derive Macro` sections.

Must have been at some point that we added that last sentence and messed it all up. Will fix.

**Comment by shawntabrizi** [comment]
Should be patched, let me know if it is more clear now or can be better improved.
