### ISSUE TITLE
Link to docs about entropy source

### ISSUE THREAD

**Issue by JoshOrndorff** [shawntabrizi/substrate-collectables-workshop#92]
> Substrate uses a safe mixing algorithm that uses the entropy of previous blocks to generate new random data for each subsequent block.

Explaining entropy and where to get it is not in scope for this tutorial, but a link would be nice. In particular I'd like to know under what assumptions the mixing algorithm is safe, and what kinds of validator collusion or other attacks might compromise it.

**Comment by JoshOrndorff** [comment]
Even a link to an implementation would suffice.

**Comment by shawntabrizi** [comment]
Conversation about the `random_seed` safety from W3F researchers here:
https://github.com/paritytech/ink/issues/57

Although, it is still not clear to me exactly when and how this can be used.

Implementation is here: https://github.com/paritytech/substrate/blob/2899be9eef8821eb1b601812c038c69d7a177f93/srml/system/src/lib.rs#L435

Although I don't honestly fully understand what is happening. But you can see we use 81 blocks to generate it.
